server:
    port: 9200
            
    servlet:
        context-path: /busqueda
        
spring:
    application:
        name: Busqueda
        description: API Busquedas
        version: 1.0
        
    datasource:        
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5439/postgres
        username: postgres
        password: 
        minimumIdle: 10
        maximumPoolSize: 100
        maxLifetime: 3600000   
        
    kafka:
        bootstrap-servers: localhost:9092
            
springdoc:
    api-docs:
        version: openapi_3_1
        path: '/v3/api-docs'  
    show-actuator: true     

    swagger-ui:
        enabled: true   
        tags-sorter: alpha
        operations-sorter: alpha

com.busqueda:
    swagger: 
        url: 'http://localhost:9200/busqueda/'     
        
    logger:
        logSqlKeywords: true
        keywords: password
        listaNegraKeywords: password, clave, generatedPassword, newPassword

