INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (1, '1234aBc', '29/12/2023', '31/12/2023');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (2, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (3, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (4, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (5, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (6, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (7, '1234aBc', '08/07/2024', '11/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (8, '77755abc', '12/07/2024', '25/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (9, '77755abc', '12/07/2024', '25/07/2024');
INSERT INTO public.busquedas (search_id, hotel_id, check_in, check_out) VALUES (10, '77755abc', '12/07/2024', '25/07/2024');

INSERT INTO public.busquedas_edades (search_id, age) VALUES (1, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (1, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (1, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (1, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (2, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (2, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (2, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (2, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (3, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (3, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (3, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (3, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (4, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (4, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (4, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (4, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (5, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (5, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (5, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (5, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (6, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (6, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (6, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (6, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (7, 30);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (7, 29);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (7, 1);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (7, 3);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (8, 42);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (8, 42);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (8, 7);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (9, 43);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (9, 42);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (9, 7);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (10, 42);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (10, 42);
INSERT INTO public.busquedas_edades (search_id, age) VALUES (10, 7);
