SET MODE PostgreSQL;

CREATE SCHEMA IF NOT EXISTS "PUBLIC";

CREATE SEQUENCE secuencia_id_busqueda start 100;

CREATE TABLE IF NOT EXISTS "PUBLIC"."BUSQUEDAS"
    (
        SEARCH_ID BIGINT NOT NULL,
        HOTEL_ID VARCHAR(20) NOT NULL,
        CHECK_IN VARCHAR(20) NOT NULL,
        CHECK_OUT VARCHAR(20) NOT NULL,
        CONSTRAINT BUSQUEDAS_PK PRIMARY KEY (SEARCH_ID)
    );

CREATE TABLE IF NOT EXISTS "PUBLIC"."BUSQUEDAS_EDADES"
    (
        ID_BUSQUEDAS_EDADES INTEGER GENERATED ALWAYS AS IDENTITY,
        SEARCH_ID INTEGER,
        AGE INTEGER,
        CONSTRAINT BUSQUEDAS_EDADES_pk PRIMARY KEY (ID_BUSQUEDAS_EDADES),
        CONSTRAINT BUSQUEDASEDADES_FK1 FOREIGN KEY (SEARCH_ID) REFERENCES "PUBLIC"."BUSQUEDAS"(SEARCH_ID)
    );